<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Framework.$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <PackageReference Include="Mapster" />
  </ItemGroup>
  <ItemGroup>
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>
 </Project>
