<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
   
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\framework\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\SampleModule.Application\SampleModule.Application.csproj" />
  </ItemGroup>

</Project>
